name: flutter_study
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # network 
  dio: ^3.0.10
  # toast
  fluttertoast: ^7.1.1
  # 状态管理
  provider: ^4.3.2+2
  # 适配
  flutter_screenutil: ^3.2.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # 下拉刷新上提加载
  pull_to_refresh: ^1.6.1
  # 加密
  crypto: ^2.1.5
  # 图片
  cached_network_image: ^2.4.1
  # webview
  webview_flutter: ^1.0.7
  # web socket
  web_socket_channel: ^1.1.0
  # 解压
  archive: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imgs/
    - imgs/icons/
    - data/example.json
    - data/example_home.json
    
    
